import { Word, WordPack } from '@/types'

function w(id: string, text: string, difficulty: Word['difficulty']): Word {
  return { id, text, difficulty }
}

export const DEFAULT_WORD_PACKS: WordPack[] = [
  {
    id: 'pack-food',
    name: 'Đồ ăn',
    emoji: '🍜',
    isDefault: true,
    words: [
      w('food-01', 'Phở', 'easy'),
      w('food-02', 'Bánh mì', 'easy'),
      w('food-03', 'Bún bò', 'easy'),
      w('food-04', 'Cơm tấm', 'easy'),
      w('food-05', 'Bánh xèo', 'medium'),
      w('food-06', 'Gỏi cuốn', 'easy'),
      w('food-07', 'Hủ tiếu', 'medium'),
      w('food-08', 'Chả giò', 'easy'),
      w('food-09', 'Xôi gà', 'medium'),
      w('food-10', 'Bánh cuốn', 'medium'),
      w('food-11', 'Lẩu', 'easy'),
      w('food-12', 'Cháo lòng', 'hard'),
      w('food-13', 'Mì Quảng', 'medium'),
      w('food-14', 'Bún riêu', 'medium'),
      w('food-15', 'Cơm chiên', 'easy'),
      w('food-16', 'Bánh tráng', 'easy'),
      w('food-17', 'Bún chả', 'medium'),
      w('food-18', 'Chè', 'easy'),
      w('food-19', 'Bánh kem', 'easy'),
      w('food-20', 'Bánh flan', 'hard'),
      w('food-21', 'Bún mắm', 'hard'),
      w('food-22', 'Bánh canh', 'medium'),
      w('food-23', 'Gỏi khô bò', 'medium'),
      w('food-24', 'Ốc luộc', 'easy'),
      w('food-25', 'Trứng vịt lộn', 'medium'),
      w('food-26', 'Bánh da lợn', 'hard'),
      w('food-27', 'Kem bơ', 'easy'),
      w('food-28', 'Rau câu', 'easy'),
      w('food-29', 'Khoai lang nướng', 'easy'),
      w('food-30', 'Bắp xào', 'easy'),
      w('food-31', 'Gà nướng', 'easy'),
      w('food-32', 'Vịt quay', 'medium'),
      w('food-33', 'Thịt kho tàu', 'medium'),
      w('food-34', 'Canh chua', 'medium'),
      w('food-35', 'Sườn bì chả', 'medium'),
      w('food-36', 'Bánh đậu xanh', 'hard'),
      w('food-37', 'Mứt gừng', 'medium'),
      w('food-38', 'Kẹo dừa', 'medium'),
      w('food-39', 'Nem chua', 'medium'),
      w('food-40', 'Chả cá Lã Vọng', 'hard'),
      w('food-41', 'Bánh khoái', 'medium'),
      w('food-42', 'Bún đậu mắm tôm', 'easy'),
      w('food-43', 'Bò kho', 'medium'),
      w('food-44', 'Gà tần', 'hard'),
      w('food-45', 'Miến lươn', 'hard'),
      w('food-46', 'Bánh bò', 'medium'),
      w('food-47', 'Xôi gấc', 'medium'),
      w('food-48', 'Bò tơ', 'hard'),
      w('food-49', 'Gỏi ngó sen', 'medium'),
      w('food-50', 'Cháo gà', 'easy'),
      w('food-51', 'Bánh giò', 'medium'),
      w('food-52', 'Bánh chưng', 'easy'),
      w('food-53', 'Bánh tét', 'easy'),
      w('food-54', 'Dưa giá', 'hard'),
      w('food-55', 'Thịt luộc', 'easy'),
      w('food-56', 'Cá kho tộ', 'medium'),
      w('food-57', 'Rau muống xào tỏi', 'easy'),
      w('food-58', 'Khổ qua nhồi thịt', 'medium'),
      w('food-59', 'Canh bí đỏ', 'easy'),
      w('food-60', 'Sữa chua nếp cẩm', 'medium'),
    ],
  },
  {
    id: 'pack-places',
    name: 'Địa danh Việt Nam',
    emoji: '🗺️',
    isDefault: true,
    words: [
      w('place-01', 'Hội An', 'easy'),
      w('place-02', 'Hạ Long', 'easy'),
      w('place-03', 'Sapa', 'easy'),
      w('place-04', 'Phú Quốc', 'easy'),
      w('place-05', 'Đà Lạt', 'easy'),
      w('place-06', 'Huế', 'easy'),
      w('place-07', 'Nha Trang', 'easy'),
      w('place-08', 'Mũi Né', 'medium'),
      w('place-09', 'Bà Nà Hills', 'hard'),
      w('place-10', 'Cần Thơ', 'medium'),
      w('place-11', 'Đà Nẵng', 'easy'),
      w('place-12', 'Hà Nội', 'easy'),
      w('place-13', 'Sài Gòn', 'easy'),
      w('place-14', 'Vũng Tàu', 'easy'),
      w('place-15', 'Ninh Bình', 'medium'),
      w('place-16', 'Phan Thiết', 'medium'),
      w('place-17', 'Côn Đảo', 'hard'),
      w('place-18', 'Mekong', 'medium'),
      w('place-19', 'Tam Cốc', 'hard'),
      w('place-20', 'Tràng An', 'hard'),
      w('place-21', 'Phong Nha', 'hard'),
      w('place-22', 'Fansipan', 'hard'),
      w('place-23', 'Đảo Lý Sơn', 'hard'),
      w('place-24', 'Quy Nhơn', 'medium'),
      w('place-25', 'Tuy Hòa', 'medium'),
      w('place-26', 'Buôn Ma Thuột', 'medium'),
      w('place-27', 'Pleiku', 'medium'),
      w('place-28', 'Kon Tum', 'medium'),
      w('place-29', 'Hà Giang', 'medium'),
      w('place-30', 'Cao Bằng', 'medium'),
      w('place-31', 'Lạng Sơn', 'medium'),
      w('place-32', 'Mộc Châu', 'easy'),
      w('place-33', 'Mai Châu', 'medium'),
      w('place-34', 'Đồng Văn', 'hard'),
      w('place-35', 'Mèo Vac', 'hard'),
      w('place-36', 'Bắc Kạn', 'hard'),
      w('place-37', 'Tuyên Quang', 'medium'),
      w('place-38', 'Yên Bái', 'medium'),
      w('place-39', 'Phú Thọ', 'medium'),
      w('place-40', 'Vĩnh Phúc', 'medium'),
      w('place-41', 'Thái Nguyên', 'medium'),
      w('place-42', 'Bắc Giang', 'medium'),
      w('place-43', 'Bắc Ninh', 'easy'),
      w('place-44', 'Quảng Ninh', 'easy'),
      w('place-45', 'Hải Dương', 'medium'),
      w('place-46', 'Hưng Yên', 'medium'),
      w('place-47', 'Hải Phòng', 'easy'),
      w('place-48', 'Thái Bình', 'medium'),
      w('place-49', 'Hà Nam', 'medium'),
      w('place-50', 'Nam Định', 'medium'),
      w('place-51', 'Thanh Hóa', 'easy'),
      w('place-52', 'Nghi Sơn', 'hard'),
      w('place-53', 'Bạch Mã', 'hard'),
      w('place-54', 'Bán đảo Sơn Trà', 'medium'),
      w('place-55', 'Ngũ Hành Sơn', 'easy'),
      w('place-56', 'Cù Lao Chàm', 'medium'),
      w('place-57', 'Tháp Chàm', 'medium'),
      w('place-58', 'Bến Tre', 'easy'),
      w('place-59', 'Đồng Tháp', 'medium'),
      w('place-60', 'Cà Mau', 'easy'),
    ],
  },
  {
    id: 'pack-animals',
    name: 'Động vật',
    emoji: '🐾',
    isDefault: true,
    words: [
      w('animal-01', 'Voi', 'easy'),
      w('animal-02', 'Hổ', 'easy'),
      w('animal-03', 'Cá sấu', 'easy'),
      w('animal-04', 'Chim công', 'medium'),
      w('animal-05', 'Gấu trúc', 'easy'),
      w('animal-06', 'Cá voi', 'easy'),
      w('animal-07', 'Tê giác', 'medium'),
      w('animal-08', 'Hươu cao cổ', 'easy'),
      w('animal-09', 'Sư tử', 'easy'),
      w('animal-10', 'Khỉ', 'easy'),
      w('animal-11', 'Rắn hổ mang', 'hard'),
      w('animal-12', 'Đại bàng', 'medium'),
      w('animal-13', 'Cá ngựa', 'medium'),
      w('animal-14', 'Bạch tuộc', 'hard'),
      w('animal-15', 'Chó sói', 'easy'),
      w('animal-16', 'Cáo', 'medium'),
      w('animal-17', 'Nai', 'easy'),
      w('animal-18', 'Cò', 'medium'),
      w('animal-19', 'Vẹt', 'easy'),
      w('animal-20', 'Hải cẩu', 'medium'),
      w('animal-21', 'Mèo', 'easy'),
      w('animal-22', 'Chó', 'easy'),
      w('animal-23', 'Thỏ', 'easy'),
      w('animal-24', 'Sóc', 'easy'),
      w('animal-25', 'Lợn lòi', 'medium'),
      w('animal-26', 'Tê tê', 'hard'),
      w('animal-27', 'Cú mèo', 'medium'),
      w('animal-28', 'Dơi', 'medium'),
      w('animal-29', 'Cá heo', 'easy'),
      w('animal-30', 'Cá mập', 'easy'),
      w('animal-31', 'Con sứa', 'medium'),
      w('animal-32', 'Sao biển', 'hard'),
      w('animal-33', 'Lạc đà', 'medium'),
      w('animal-34', 'Ngựa vằn', 'medium'),
      w('animal-35', 'Hà mã', 'medium'),
      w('animal-36', 'Kiến', 'easy'),
      w('animal-37', 'Ong', 'easy'),
      w('animal-38', 'Nhện', 'easy'),
      w('animal-39', 'Chuồn chuồn', 'medium'),
      w('animal-40', 'Bọ cánh cứng', 'hard'),
      w('animal-41', 'Đà điểu', 'medium'),
      w('animal-42', 'Cừu', 'easy'),
      w('animal-43', 'Dê', 'easy'),
      w('animal-44', 'Ngựa', 'easy'),
      w('animal-45', 'Bò tót', 'hard'),
      w('animal-46', 'Tê giác trăng', 'hard'),
      w('animal-47', 'Sư tử biển', 'medium'),
      w('animal-48', 'Cá lăng', 'hard'),
      w('animal-49', 'Lươn', 'medium'),
      w('animal-50', 'Chim bồ câu', 'easy'),
      w('animal-51', 'Chim gõ kiến', 'hard'),
      w('animal-52', 'Chim hải âu', 'medium'),
      w('animal-53', 'Chim cánh cụt', 'easy'),
      w('animal-54', 'Gấu Bắc Cực', 'easy'),
      w('animal-55', 'Gấu xám', 'medium'),
      w('animal-56', 'Tinh tinh', 'medium'),
      w('animal-57', 'Đười ươi', 'hard'),
      w('animal-58', 'Hươu sao', 'medium'),
      w('animal-59', 'Tuần lộc', 'medium'),
      w('animal-60', 'Chuột túi', 'easy'),
      w('animal-61', 'Gấu túi', 'medium'),
      w('animal-62', 'Nhím', 'medium'),
      w('animal-63', 'Tắc kè', 'hard'),
      w('animal-64', 'Kỳ đà', 'hard'),
      w('animal-65', 'Ba ba', 'medium'),
    ],
  },
  {
    id: 'pack-movies',
    name: 'Phim & Series',
    emoji: '🎬',
    isDefault: true,
    words: [
      w('movie-01', 'Ký sinh trùng', 'hard'),
      w('movie-02', 'Avengers', 'easy'),
      w('movie-03', 'Squid Game', 'easy'),
      w('movie-04', 'Titanic', 'easy'),
      w('movie-05', 'Avatar', 'easy'),
      w('movie-06', 'Harry Potter', 'easy'),
      w('movie-07', 'Game of Thrones', 'easy'),
      w('movie-08', 'Friends', 'easy'),
      w('movie-09', 'La La Land', 'medium'),
      w('movie-10', 'Joker', 'easy'),
      w('movie-11', 'Inception', 'medium'),
      w('movie-12', 'The Batman', 'medium'),
      w('movie-13', 'Stranger Things', 'medium'),
      w('movie-14', 'Money Heist', 'medium'),
      w('movie-15', 'Interstellar', 'hard'),
      w('movie-16', 'Black Panther', 'medium'),
      w('movie-17', 'Toy Story', 'easy'),
      w('movie-18', 'The Lion King', 'easy'),
      w('movie-19', 'Forrest Gump', 'hard'),
      w('movie-20', 'The Godfather', 'hard'),
      w('movie-21', 'Spiderman', 'easy'),
      w('movie-22', 'Iron Man', 'easy'),
      w('movie-23', 'Batman', 'easy'),
      w('movie-24', 'Superman', 'easy'),
      w('movie-25', 'Finding Nemo', 'easy'),
      w('movie-26', 'Frozen', 'easy'),
      w('movie-27', 'Shrek', 'easy'),
      w('movie-28', 'Despicable Me', 'easy'),
      w('movie-29', 'Star Wars', 'medium'),
      w('movie-30', 'Jurrasic Park', 'medium'),
      w('movie-31', 'The Witcher', 'medium'),
      w('movie-32', 'Black Mirror', 'hard'),
      w('movie-33', 'Breaking Bad', 'medium'),
      w('movie-34', 'Better Call Saul', 'hard'),
      w('movie-35', 'Narcos', 'medium'),
      w('movie-36', 'Dark', 'hard'),
      w('movie-37', 'The Crown', 'medium'),
      w('movie-38', 'Succession', 'hard'),
      w('movie-39', 'Ted Lasso', 'medium'),
      w('movie-40', 'The Bear', 'medium'),
      w('movie-41', 'Dune', 'medium'),
      w('movie-42', 'Oppenheimer', 'hard'),
      w('movie-43', 'Barbie', 'easy'),
      w('movie-44', 'Parasite', 'hard'),
      w('movie-45', 'John Wick', 'easy'),
      w('movie-46', 'Top Gun', 'easy'),
      w('movie-47', 'Mission Impossible', 'medium'),
      w('movie-48', 'Fast & Furious', 'easy'),
      w('movie-49', 'Jurassic World', 'medium'),
      w('movie-50', 'Guardians of the Galaxy', 'medium'),
      w('movie-51', 'Up', 'easy'),
      w('movie-52', 'Inside Out', 'easy'),
      w('movie-53', 'Coco', 'easy'),
      w('movie-54', 'Moana', 'easy'),
      w('movie-55', 'Spider-Verse', 'medium'),
      w('movie-56', 'Everything Everywhere All At Once', 'hard'),
      w('movie-57', 'The Last of Us', 'medium'),
      w('movie-58', 'The Mandalorian', 'medium'),
      w('movie-59', 'Wednesday', 'easy'),
      w('movie-60', 'Beef', 'hard'),
    ],
  },
  {
    id: 'pack-world',
    name: 'Thế giới xung quanh',
    emoji: '🌍',
    isDefault: true,
    words: [
      w('world-01', 'Xe máy', 'easy'),
      w('world-02', 'Điện thoại', 'easy'),
      w('world-03', 'Cây cầu', 'easy'),
      w('world-04', 'Máy bay', 'easy'),
      w('world-05', 'Tòa nhà', 'easy'),
      w('world-06', 'Bệnh viện', 'easy'),
      w('world-07', 'Trường học', 'easy'),
      w('world-08', 'Siêu thị', 'easy'),
      w('world-09', 'Xe buýt', 'easy'),
      w('world-10', 'Đèn giao thông', 'medium'),
      w('world-11', 'Thang máy', 'medium'),
      w('world-12', 'Máy tính', 'easy'),
      w('world-13', 'Tivi', 'easy'),
      w('world-14', 'Tủ lạnh', 'easy'),
      w('world-15', 'Máy giặt', 'medium'),
      w('world-16', 'Xe đạp', 'easy'),
      w('world-17', 'Ô tô', 'easy'),
      w('world-18', 'Tàu hỏa', 'medium'),
      w('world-19', 'Xe tải', 'medium'),
      w('world-20', 'Tàu thủy', 'medium'),
      w('world-21', 'Internet', 'medium'),
      w('world-22', 'Wifi', 'medium'),
      w('world-23', 'Vệ tinh', 'hard'),
      w('world-24', 'Kính viễn vọng', 'hard'),
      w('world-25', 'Pin mặt trời', 'hard'),
      w('world-26', 'Máy ảnh', 'medium'),
      w('world-27', 'Ống nhòm', 'medium'),
      w('world-28', 'La bàn', 'medium'),
      w('world-29', 'Máy sấy tóc', 'easy'),
      w('world-30', 'Bàn là', 'easy'),
      w('world-31', 'Thang cuốn', 'medium'),
      w('world-32', 'Vỉa hè', 'easy'),
      w('world-33', 'Công viên', 'easy'),
      w('world-34', 'Rạp chiếu phim', 'easy'),
      w('world-35', 'Ngân hàng', 'easy'),
      w('world-36', 'Nhà ga', 'medium'),
      w('world-37', 'Sân bay', 'easy'),
      w('world-38', 'Bến cảng', 'medium'),
      w('world-39', 'Đường cao tốc', 'medium'),
      w('world-40', 'Cầu vượt', 'medium'),
      w('world-41', 'Đường hầm', 'hard'),
      w('world-42', 'Nhà máy', 'medium'),
      w('world-43', 'Trạm xăng', 'easy'),
      w('world-44', 'Bưu điện', 'easy'),
      w('world-45', 'Thư viện', 'easy'),
      w('world-46', 'Bảo tàng', 'medium'),
      w('world-47', 'Sân vận động', 'medium'),
      w('world-48', 'Quảng trường', 'medium'),
      w('world-49', 'Nhà thờ', 'easy'),
      w('world-50', 'Chùa', 'easy'),
      w('world-51', 'Khách sạn', 'easy'),
      w('world-52', 'Nhà hàng', 'easy'),
      w('world-53', 'Quán cà phê', 'easy'),
      w('world-54', 'Trung tâm thương mại', 'medium'),
      w('world-55', 'Công trường', 'medium'),
      w('world-56', 'Trạm vũ trụ', 'hard'),
      w('world-57', 'Hải đăng', 'hard'),
      w('world-58', 'Tháp truyền hình', 'hard'),
      w('world-59', 'Nhà kính', 'medium'),
      w('world-60', 'Cối xay gió', 'hard'),
    ],
  },
  {
    id: 'pack-jobs',
    name: 'Nghề nghiệp',
    emoji: '👨‍💼',
    isDefault: true,
    words: [
      w('job-01', 'Bác sĩ', 'easy'),
      w('job-02', 'Giáo viên', 'easy'),
      w('job-03', 'Cảnh sát', 'easy'),
      w('job-04', 'Đầu bếp', 'easy'),
      w('job-05', 'Họa sĩ', 'medium'),
      w('job-06', 'Nhạc sĩ', 'medium'),
      w('job-07', 'Kỹ sư', 'medium'),
      w('job-08', 'Nông dân', 'easy'),
      w('job-09', 'Phi công', 'medium'),
      w('job-10', 'Luật sư', 'hard'),
      w('job-11', 'Thợ làm tóc', 'medium'),
      w('job-12', 'Vận động viên', 'easy'),
      w('job-13', 'Nhà du hành', 'hard'),
      w('job-14', 'Lính cứu hỏa', 'easy'),
      w('job-15', 'Nhiếp ảnh gia', 'medium'),
      w('job-16', 'Bác sĩ thú y', 'medium'),
      w('job-17', 'Lập trình viên', 'medium'),
      w('job-18', 'Kiến trúc sư', 'hard'),
      w('job-19', 'Thợ mộc', 'medium'),
      w('job-20', 'Thợ may', 'medium'),
      w('job-21', 'Kế toán', 'medium'),
      w('job-22', 'Giám đốc', 'medium'),
      w('job-23', 'Thư ký', 'easy'),
      w('job-24', 'Nhân viên bán hàng', 'easy'),
      w('job-25', 'Bảo vệ', 'easy'),
      w('job-26', 'Tài xế', 'easy'),
      w('job-27', 'Phiên dịch viên', 'hard'),
      w('job-28', 'Hướng dẫn viên du lịch', 'medium'),
      w('job-29', 'Nhà báo', 'medium'),
      w('job-30', 'Phóng viên', 'medium'),
      w('job-31', 'Biên tập viên', 'hard'),
      w('job-32', 'Thợ điện', 'medium'),
      w('job-33', 'Thợ sửa ống nước', 'medium'),
      w('job-34', 'Thợ cơ khí', 'medium'),
      w('job-35', 'Thợ xây', 'medium'),
      w('job-36', 'Thợ sơn', 'easy'),
      w('job-37', 'Người mẫu', 'medium'),
      w('job-38', 'Diễn viên', 'medium'),
      w('job-39', 'Ca sĩ', 'easy'),
      w('job-40', 'Vũ công', 'medium'),
      w('job-41', 'Nhà tạo mẫu', 'hard'),
      w('job-42', 'Chuyên gia trang điểm', 'medium'),
      w('job-43', 'Dược sĩ', 'medium'),
      w('job-44', 'Y tá', 'easy'),
      w('job-45', 'Nha sĩ', 'medium'),
      w('job-46', 'Nhà tâm lý học', 'hard'),
      w('job-47', 'Nhà kinh tế', 'hard'),
      w('job-48', 'Nhà khoa học', 'hard'),
      w('job-49', 'Nhà nghiên cứu', 'hard'),
      w('job-50', 'Giảng viên đại học', 'hard'),
      w('job-51', 'Huấn luyện viên', 'medium'),
      w('job-52', 'Trọng tài', 'medium'),
      w('job-53', 'Thủ tề', 'hard'),
      w('job-54', 'Phục vụ bàn', 'easy'),
      w('job-55', 'Lễ tân', 'easy'),
      w('job-56', 'Nhân viên ngân hàng', 'medium'),
      w('job-57', 'Nhân viên bảo hiểm', 'medium'),
      w('job-58', 'Bôi giới nhà đất', 'medium'),
      w('job-59', 'Kiểm toán viên', 'hard'),
      w('job-60', 'Lãnh sự', 'hard'),
    ],
  },
  {
    id: 'pack-objects',
    name: 'Vật dụng',
    emoji: '🪑',
    isDefault: true,
    words: [
      w('obj-01', 'Bàn', 'easy'),
      w('obj-02', 'Ghế', 'easy'),
      w('obj-03', 'Giường', 'easy'),
      w('obj-04', 'Tủ', 'easy'),
      w('obj-05', 'Đèn', 'easy'),
      w('obj-06', 'Gương', 'medium'),
      w('obj-07', 'Đồng hồ', 'easy'),
      w('obj-08', 'Chổi', 'easy'),
      w('obj-09', 'Khăn tắm', 'medium'),
      w('obj-10', 'Bàn chải', 'medium'),
      w('obj-11', 'Lược', 'easy'),
      w('obj-12', 'Kéo', 'medium'),
      w('obj-13', 'Dao', 'easy'),
      w('obj-14', 'Thìa', 'easy'),
      w('obj-15', 'Nĩa', 'medium'),
      w('obj-16', 'Ly', 'easy'),
      w('obj-17', 'Chén', 'easy'),
      w('obj-18', 'Nồi', 'medium'),
      w('obj-19', 'Ấm đun nước', 'hard'),
      w('obj-20', 'Máy điều hòa', 'hard'),
      w('obj-21', 'Quạt', 'easy'),
      w('obj-22', 'Tivi', 'easy'),
      w('obj-23', 'Tủ lạnh', 'easy'),
      w('obj-24', 'Máy giặt', 'medium'),
      w('obj-25', 'Lò vi sóng', 'medium'),
      w('obj-26', 'Máy hút bụi', 'medium'),
      w('obj-27', 'Bàn là', 'easy'),
      w('obj-28', 'Máy sấy tóc', 'easy'),
      w('obj-29', 'Máy pha cà phê', 'hard'),
      w('obj-30', 'Máy xay sinh tố', 'medium'),
      w('obj-31', 'Thảm', 'easy'),
      w('obj-32', 'Rèm cửa', 'medium'),
      w('obj-33', 'Gối', 'easy'),
      w('obj-34', 'Chăn', 'easy'),
      w('obj-35', 'Nệm', 'medium'),
      w('obj-36', 'Giá sách', 'medium'),
      w('obj-37', 'Bàn làm việc', 'medium'),
      w('obj-38', 'Ghế xoay', 'medium'),
      w('obj-39', 'Đồ chơi', 'easy'),
      w('obj-40', 'Tranh treo tường', 'medium'),
      w('obj-41', 'Chậu hoa', 'easy'),
      w('obj-42', 'Cây cảnh', 'easy'),
      w('obj-43', 'Bình hoa', 'medium'),
      w('obj-44', 'Kệ giày', 'easy'),
      w('obj-45', 'Móc quần áo', 'easy'),
      w('obj-46', 'Xô', 'easy'),
      w('obj-47', 'Chậu', 'easy'),
      w('obj-48', 'Vòi nước', 'medium'),
      w('obj-49', 'Bồn cầu', 'easy'),
      w('obj-50', 'Bồn tắm', 'medium'),
      w('obj-51', 'Khăn trải bàn', 'hard'),
      w('obj-52', 'Lọ đựng gia vị', 'hard'),
      w('obj-53', 'Thớt', 'medium'),
      w('obj-54', 'Rổ', 'easy'),
      w('obj-55', 'Bình giữ nhiệt', 'hard'),
      w('obj-56', 'Hộp đựng cơm', 'medium'),
      w('obj-57', 'Ô (Dù)', 'easy'),
      w('obj-58', 'Áo mưa', 'easy'),
      w('obj-59', 'Đèn pin', 'medium'),
      w('obj-60', 'Pin', 'easy'),
    ],
  },
]
