import { Word, WordPack } from '@/types'

function w(id: string, text: string, difficulty: Word['difficulty']): Word {
  return { id, text, difficulty }
}

export const DEFAULT_WORD_PACKS: WordPack[] = [
  {
    id: 'pack-food',
    name: 'Đồ ăn',
    emoji: '🍜',
    isDefault: true,
    words: [
      w('food-01', 'Phở', 'easy'),
      w('food-02', 'Bánh mì', 'easy'),
      w('food-03', 'Bún bò', 'easy'),
      w('food-04', 'Cơm tấm', 'easy'),
      w('food-05', 'Bánh xèo', 'medium'),
      w('food-06', 'Gỏi cuốn', 'easy'),
      w('food-07', 'Hủ tiếu', 'medium'),
      w('food-08', 'Chả giò', 'easy'),
      w('food-09', 'Xôi gà', 'medium'),
      w('food-10', 'Bánh cuốn', 'medium'),
      w('food-11', 'Lẩu', 'easy'),
      w('food-12', 'Cháo lòng', 'hard'),
      w('food-13', 'Mì Quảng', 'medium'),
      w('food-14', 'Bún riêu', 'medium'),
      w('food-15', 'Cơm chiên', 'easy'),
      w('food-16', 'Bánh tráng', 'easy'),
      w('food-17', 'Bún chả', 'medium'),
      w('food-18', 'Chè', 'easy'),
      w('food-19', 'Bánh kem', 'easy'),
      w('food-20', 'Bánh flan', 'hard'),
    ],
  },
  {
    id: 'pack-places',
    name: 'Địa danh Việt Nam',
    emoji: '🗺️',
    isDefault: true,
    words: [
      w('place-01', 'Hội An', 'easy'),
      w('place-02', 'Hạ Long', 'easy'),
      w('place-03', 'Sapa', 'easy'),
      w('place-04', 'Phú Quốc', 'easy'),
      w('place-05', 'Đà Lạt', 'easy'),
      w('place-06', 'Huế', 'easy'),
      w('place-07', 'Nha Trang', 'easy'),
      w('place-08', 'Mũi Né', 'medium'),
      w('place-09', 'Bà Nà Hills', 'hard'),
      w('place-10', 'Cần Thơ', 'medium'),
      w('place-11', 'Đà Nẵng', 'easy'),
      w('place-12', 'Hà Nội', 'easy'),
      w('place-13', 'Sài Gòn', 'easy'),
      w('place-14', 'Vũng Tàu', 'easy'),
      w('place-15', 'Ninh Bình', 'medium'),
      w('place-16', 'Phan Thiết', 'medium'),
      w('place-17', 'Côn Đảo', 'hard'),
      w('place-18', 'Mekong', 'medium'),
      w('place-19', 'Tam Cốc', 'hard'),
      w('place-20', 'Tràng An', 'hard'),
    ],
  },
  {
    id: 'pack-animals',
    name: 'Động vật',
    emoji: '🐾',
    isDefault: true,
    words: [
      w('animal-01', 'Voi', 'easy'),
      w('animal-02', 'Hổ', 'easy'),
      w('animal-03', 'Cá sấu', 'easy'),
      w('animal-04', 'Chim công', 'medium'),
      w('animal-05', 'Gấu trúc', 'easy'),
      w('animal-06', 'Cá voi', 'easy'),
      w('animal-07', 'Tê giác', 'medium'),
      w('animal-08', 'Hươu cao cổ', 'easy'),
      w('animal-09', 'Sư tử', 'easy'),
      w('animal-10', 'Khỉ', 'easy'),
      w('animal-11', 'Rắn hổ mang', 'hard'),
      w('animal-12', 'Đại bàng', 'medium'),
      w('animal-13', 'Cá ngựa', 'medium'),
      w('animal-14', 'Bạch tuộc', 'hard'),
      w('animal-15', 'Chó sói', 'easy'),
      w('animal-16', 'Cáo', 'medium'),
      w('animal-17', 'Nai', 'easy'),
      w('animal-18', 'Cò', 'medium'),
      w('animal-19', 'Vẹt', 'easy'),
      w('animal-20', 'Hải cẩu', 'medium'),
    ],
  },
  {
    id: 'pack-movies',
    name: 'Phim & Series',
    emoji: '🎬',
    isDefault: true,
    words: [
      w('movie-01', 'Ký sinh trùng', 'hard'),
      w('movie-02', 'Avengers', 'easy'),
      w('movie-03', 'Squid Game', 'easy'),
      w('movie-04', 'Titanic', 'easy'),
      w('movie-05', 'Avatar', 'easy'),
      w('movie-06', 'Harry Potter', 'easy'),
      w('movie-07', 'Game of Thrones', 'easy'),
      w('movie-08', 'Friends', 'easy'),
      w('movie-09', 'La La Land', 'medium'),
      w('movie-10', 'Joker', 'easy'),
      w('movie-11', 'Inception', 'medium'),
      w('movie-12', 'The Batman', 'medium'),
      w('movie-13', 'Stranger Things', 'medium'),
      w('movie-14', 'Money Heist', 'medium'),
      w('movie-15', 'Interstellar', 'hard'),
      w('movie-16', 'Black Panther', 'medium'),
      w('movie-17', 'Toy Story', 'easy'),
      w('movie-18', 'The Lion King', 'easy'),
      w('movie-19', 'Forrest Gump', 'hard'),
      w('movie-20', 'The Godfather', 'hard'),
    ],
  },
  {
    id: 'pack-world',
    name: 'Thế giới xung quanh',
    emoji: '🌍',
    isDefault: true,
    words: [
      w('world-01', 'Xe máy', 'easy'),
      w('world-02', 'Điện thoại', 'easy'),
      w('world-03', 'Cây cầu', 'easy'),
      w('world-04', 'Máy bay', 'easy'),
      w('world-05', 'Tòa nhà', 'easy'),
      w('world-06', 'Bệnh viện', 'easy'),
      w('world-07', 'Trường học', 'easy'),
      w('world-08', 'Siêu thị', 'easy'),
      w('world-09', 'Xe buýt', 'easy'),
      w('world-10', 'Đèn giao thông', 'medium'),
      w('world-11', 'Thang máy', 'medium'),
      w('world-12', 'Máy tính', 'easy'),
      w('world-13', 'Tivi', 'easy'),
      w('world-14', 'Tủ lạnh', 'easy'),
      w('world-15', 'Máy giặt', 'medium'),
      w('world-16', 'Xe đạp', 'easy'),
      w('world-17', 'Ô tô', 'easy'),
      w('world-18', 'Tàu hỏa', 'medium'),
      w('world-19', 'Xe tải', 'medium'),
      w('world-20', 'Tàu thủy', 'medium'),
    ],
  },
]
